### ISSUE TITLE
ModuleNotFoundError: No module named 'optionchain'

### ISSUE THREAD

**Issue by geofffoster** [juxeii/ibtools#1]
Fresh install in anaconda virtual environment

import ibtools as ibt

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-911ef87ff70c> in <module>
      2 display(HTML("<style>.container { width:100% !important; }</style>"))
      3 
----> 4 import ibtools as ibt
      5 
      6 # import os

~/anaconda3/envs/ML5/lib/python3.6/site-packages/ibtools/__init__.py in <module>
----> 1 from optionchain import setApplication
      2 from optionchain import getOptionContracts
      3 from optionchain import getOptionContractsInDateRange
      4 from optionchain import getOptionContractsInDaysRange
      5 from optionchain import getOptionContractsUpUntilDays

ModuleNotFoundError: No module named 'optionchain'

**Comment by juxeii** [comment]
Hi,

please try with attached whl file.
Download the file and save it somewhere.
Remove the zip file ending such that the file name is now` ibtools-0.6-py3-none-any.whl`.
Then open your anaconda command prompt at this location and do:
```
1) pip uninstall ibtools
2) pip install --upgrade ibtools-0.6-py3-none-any.whl
```
Ignore all errors and try again.
Please note that function signatures have changed, but at least the import statement should work.
[ibtools-0.6-py3-none-any.whl.zip](https://github.com/juxeii/ibtools/files/6177879/ibtools-0.6-py3-none-any.whl.zip)

**Comment by geofffoster** [comment]
done - but now I get

----> 4 import ibtools as ibt
      5 
      6 # import os

~/anaconda3/envs/ML5/lib/python3.6/site-packages/ibtools/__init__.py in <module>
----> 1 from tools import OptionDetail
      2 from tools import setApplication
      3 
      4 from optionchain import OptionChain
      5 from optionchain import getOptionChains

ModuleNotFoundError: No module named 'tools'


in the filesystem I can see - 

geoff@geoff-P1:~/anaconda3/envs/ML5/lib/python3.6/site-packages/ibtools$ ls -tral
total 76
-rw-rw-r--   1 geoff geoff  1346 Mar 21 16:51 tools.py
-rw-rw-r--   1 geoff geoff  7334 Mar 21 16:51 optionsnapshot.py
-rw-rw-r--   1 geoff geoff  7109 Mar 21 16:51 optionchain.py
-rw-rw-r--   1 geoff geoff   494 Mar 21 16:51 __init__.py
drwxrwxr-x 839 geoff geoff 40960 Mar 21 16:51 ..
drwxrwxr-x   3 geoff geoff  4096 Mar 21 16:51 .
drwxrwxr-x   2 geoff geoff  4096 Mar 21 16:51 __pycache__
(base) geoff@geoff-P1:~/anaconda3/envs/ML5/lib/python3.6/site-packages/ibtools$

**Comment by juxeii** [comment]
Please try again with attached file.
Please remove the old package completely from your syspath.
[ibtools-0.6-py3-none-any.whl.zip](https://github.com/juxeii/ibtools/files/6178004/ibtools-0.6-py3-none-any.whl.zip)

**Comment by geofffoster** [comment]
working - thanks for the fast help

**Comment by juxeii** [comment]
If you have more questions/issues, please contact me under juxeii@gmx.de directly.
The software is in total beta state, would be great if you can help testing ;)
