### ISSUE TITLE
caching algorithm assumes no new strikes are created as time moves on in a given option chain

### ISSUE THREAD

**Issue by bayareacoder** [juxeii/ibtools#5]
The disk caching algorithm assumes that when we find an option chain stored on disk for a valid expiration date in the option chains request, that we then can just return the cached option chain, which will have all valid option contracts from the time the caching was done.
So if a market maker creates options in an option chain with new strikes after the caching was done (eg as a result of the underlying moving by a certain %) then those will never be present. 

In function `_chainsForValidDates` in `optionChain.py`:
```
    if len(cachedChains) == len(validDates):
        return cachedChains
    newChains = _newChainsFromTwsChains(underlying, twsChains, validDates, cachedChains)
    return _serializeAndReturnChains(underlying, cachedChains, newChains, storedChains)
```

This could be an issue for any trading strategy that uses deep OTM options, especially longer-term.
I don't see an easy way to fix, since the IB API doesn't give you an easy way to determine valid strikes by exp date and you would need to run ib-insync's `qualifyContracts` on each option contract, which of course defeats the purpose of buffering.

But for practical purposes, it may be sufficient to point out this issue, and just add an API to clear the buffer (erase the cache files) if they are older than X days.

**Comment by juxeii** [comment]
Hi,
I no longer work on/support this repo.
I see you are very active here, so I suggest that you fork it and continue to improve it from there on.
Many users will be greatful for your work and proposals, keep up the motivation :)

**Comment by bayareacoder** [comment]
Closing issue since author commented this repo is no longer maintained
